FROM python:3.8

# 기본 패키지 설치
RUN pip install --no-cache-dir google-cloud-bigquery google-cloud-storage pandas

# 작업 디렉토리 설정
WORKDIR /opt/bigquery

# 스크립트 복사
COPY ./src/bigquery /opt/bigquery

# GCP 인증 키 추가
COPY ./keys/gcs-key.json /opt/keys/gcs-key.json

# 환경 변수 설정
ENV GOOGLE_APPLICATION_CREDENTIALS="/opt/keys/gcs-key.json"

# 실행 명령어
CMD ["python3", "bigquery_optimization.py"]