version: "3.8"

services:
  airflow:
    image: apache/airflow:2.6.1
    container_name: airflow
    restart: always
    environment:
      - LOAD_EX=n
      - AIRFLOW__CORE__EXECUTOR=LocalExecutor
    ports:
      - "8080:8080"
    volumes:
      - ./airflow/dags:/opt/airflow/dags
      - ./airflow/logs:/opt/airflow/logs
      - ./airflow/plugins:/opt/airflow/plugins

  spark:
    image: bitnami/spark:3.3.1
    container_name: spark
    environment:
      - SPARK_MODE=master
    ports:
      - "7077:7077"
      - "8081:8081"
    volumes:
      - ./spark/data:/opt/spark/data

  postgres:
    image: postgres:13
    container_name: postgres
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
      POSTGRES_DB: stock_db
    ports:
      - "5432:5432"
    volumes:
      - ./postgres/data:/var/lib/postgresql/data

  bigquery:
    image: google/cloud-sdk:latest
    container_name: bigquery
    command: tail -f /dev/null
    volumes:
      - ~/.config/gcloud:/root/.config/gcloud
