services:
  # airflow:
  #   image: apache/airflow:2.6.1
  #   container_name: airflow
  #   restart: always
  #   env_file:
  #     - .env
  #   environment:
  #     - LOAD_EX=n
  #     - AIRFLOW__CORE__EXECUTOR=LocalExecutor
  #     - GOOGLE_APPLICATION_CREDENTIALS=${GOOGLE_APPLICATION_CREDENTIALS}
  #   ports:
  #     - "8080:8080"
  #   volumes:
  #     - ./airflow/dags:/opt/airflow/dags
  #     - ./airflow/logs:/opt/airflow/logs
  #     - ./airflow/plugins:/opt/airflow/plugins
  #     - ./keys:/opt/keys

  spark-master:
    build:
      context: .
      dockerfile: Dockerfile.spark
    image: spark-custom
    container_name: spark-master
    env_file:
      - .env
    environment:
      - SPARK_MODE=master
      - SPARK_MASTER_PORT=7077
      - SPARK_MASTER_WEBUI_PORT=8081
      - GOOGLE_APPLICATION_CREDENTIALS=/opt/keys/gcs-key.json
      - SPARK_CLASSPATH=/opt/spark/jars/gcs-connector-hadoop3-latest.jar
    ports:
      - "7077:7077"
      - "8081:8081"
    volumes:
      - ./spark/data:/spark/data
      - ./data:/opt/spark/data
      - "./src:/opt/src"
      - "./keys/gcs-key.json:/opt/keys/gcs-key.json"

  spark-worker:
    image: bitnami/spark:3.3.1
    container_name: spark-worker
    depends_on:
      - spark-master
    env_file:
      - .env
    environment:
      - SPARK_MODE=worker
      - SPARK_MASTER_URL=spark://spark-master:7077
      - GOOGLE_APPLICATION_CREDENTIALS=${GOOGLE_APPLICATION_CREDENTIALS}
    volumes:
      - ./keys:/opt/keys

  # bigquery:
  #   image: google/cloud-sdk:latest
  #   container_name: bigquery
  #   command: tail -f /dev/null
  #   env_file:
  #     - .env
  #   volumes:
  #     - ~/.config/gcloud:/root/.config/gcloud
  #     - ./keys:/opt/keys
